version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - helpdesk

  service-discovery:
    container_name: 'service-discovery'
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    expose:
      - 8761
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://service-discovery:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - helpdesk

  config-server:
    container_name: 'config-server'
    build:
      context: ./config-server
      dockerfile: Dockerfile
    environment:
      - CONFIG_SERVER_URI=https://github.com/ValdirCezar/formacao-backend-expert-configs
      - CONFIG_SERVER_USERNAME=valdir_cezar
      - CONFIG_SERVER_PASSWORD=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
      - EUREKA_URI=http://service-discovery:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config-server:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      service-discovery:
        condition: service_healthy
    networks:
      - helpdesk

#  api-gateway:
#    image: valdircezar/helpdesk-api-gateway
#    container_name: 'api-gateway'
#    environment:
#      - SERVER_PORT=8765
#      - EUREKA_URI=http://service-discovery:8761/eureka
#    ports:
#      - "8765:8765"
#    expose:
#      - 8765
#    depends_on:
#      - service-discovery
#    networks:
#      - helpdesk
#


networks:
  helpdesk:
    driver: bridge