version: '3'
services:
  config-server:
    image: openjdk:20-jdk
    build:
      context: ./config-server
    environment:
      - CONFIG_SERVER_URI=https://github.com/ValdirCezar/formacao-backend-expert-configs
      - CONFIG_SERVER_USERNAME=valdir_cezar
      - CONFIG_SERVER_PASSWORD=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
    ports:
      - "8888:8888"
    networks:
      - helpdesk-network

  service-discovery:
    image: openjdk:20-jdk
    build:
      context: ./service-discovery
    depends_on:
      - config-server
    networks:
      - helpdesk-network

  user-service-api:
    image: openjdk:20-jdk
    build:
      context: ./user-service-api
    depends_on:
      - service-discovery
    networks:
      - helpdesk-network

  auth-service-api:
    image: openjdk:20-jdk
    build:
      context: ./auth-service-api
    depends_on:
      - service-discovery
    networks:
      - helpdesk-network

  order-service-api:
    image: openjdk:20-jdk
    build:
      context: ./order-service-api
    depends_on:
      - auth-service-api
    networks:
      - helpdesk-network

networks:
  helpdesk-network:
    driver: bridge
