version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - helpdesk

  service-discovery:
    container_name: 'service-discovery'
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    expose:
      - 8761
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://service-discovery:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - helpdesk

  config-server:
    container_name: 'config-server'
    build:
      context: ./config-server
      dockerfile: Dockerfile
    environment:
      - CONFIG_SERVER_URI=https://github.com/ValdirCezar/formacao-backend-expert-configs
      - CONFIG_SERVER_USERNAME=valdir_cezar
      - CONFIG_SERVER_PASSWORD=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
      - EUREKA_URI=http://service-discovery:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config-server:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      service-discovery:
        condition: service_healthy
    networks:
      - helpdesk

  api-gateway:
    container_name: 'api-gateway'
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      - EUREKA_URI=http://service-discovery:8761/eureka
      - CONFIG_SERVER_URI=http://config-server:8888
    ports:
      - "8765:8765"
    expose:
      - 8765
    depends_on:
      service-discovery:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - helpdesk

  auth-service-api:
    container_name: 'auth-service-api'
    build:
      context: ./auth-service-api
      dockerfile: Dockerfile
    environment:
      - PROFILE_ACTIVE=dev
      - EUREKA_URI=http://service-discovery:8761/eureka
      - CONFIG_SERVER_URI=http://config-server:8888
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      service-discovery:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - helpdesk

  email-service:
    container_name: 'email-service'
    build:
      context: ./email-service
      dockerfile: Dockerfile
    environment:
      - PROFILE_ACTIVE=dev
      - RABBITMQ_PORT=5672
      - RABBITMQ_ADDRESSES=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - EUREKA_URI=http://service-discovery:8761/eureka
      - CONFIG_SERVER_URI=http://config-server:8888
    depends_on:
      config-server:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - helpdesk

  user-service-api:
    container_name: 'user-service-api'
    build:
      context: ./user-service-api
      dockerfile: Dockerfile
    environment:
      - PROFILE_ACTIVE=dev
      - EUREKA_URI=http://service-discovery:8761/eureka
      - CONFIG_SERVER_URI=http://config-server:8888
    depends_on:
      config-server:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
    networks:
      - helpdesk

networks:
  helpdesk:
    driver: bridge