spring:
  application:
    name: 'user-service-api'
  data:
    mongodb:
      uri: 'mongodb+srv://help-desk-user:help-desk-user@clusterhelpdesk.g07zalg.mongodb.net/helpdeskdb?retryWrites=true&w=majority'
      auto-index-creation: true