spring:
  application:
    name: 'order-service-api'
  profiles:
    active: ${PROFILE_ACTIVE}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      connect-timeout: 10000
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    connection-timeout: ${RABBITMQ_CONNECTION_TIMEOUT:10000}