spring:
  application:
    name: 'order-service-api'
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo