spring:
  application:
    name: 'config-server'
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: ${CONFIG_SERVER_URI}
          username: ${CONFIG_SERVER_USERNAME}
          password: ${CONFIG_SERVER_PASSWORD}
eureka:
  client:
    service-url:
      fetch-registry: true
      register-with-eureka: true
      defaultZone: ${EUREKA_URI}
server:
  port: ${PORT:8888}