spring:
  application:
    name: 'email-service'

mail:
  host: ${MAIL_HOST:smtp.gmail.com}
  port: ${MAIL_PORT:587}
  username: ${MAIL_USERNAME:valdircezarjesus@gmail.com}
  password: ${MAIL_PASSWORD:objn xyea tzyf ngpf}
  protocol: ${MAIL_PROTOCOL:smtp}